---
cilium_chart_repo: "https://helm.cilium.io/"
cilium_chart_name: "cilium"
cilium_namespace: "kube-system"

cilium_helmrelease_path: "../../kubernetes/cluster-0/base-apps/kube-system/cilium/app/helmrelease.yaml"
cilium_values_files:
  - "../../kubernetes/cluster-0/base-apps/kube-system/cilium/app/values.yaml"
  - "../../kubernetes/cluster-0/base-apps/kube-system/cilium/app/values-no-dashboards.yaml"
