---
- name: Fetch kubeconfig from controller
  gather_facts: true
  hosts: initial_controller
  roles:
    - fetch_kubeconfig

- name: Deploy base extensions
  gather_facts: true
  hosts: initial_controller
  roles:
    - deploy_cilium
    - deploy_openebs
